name: linters

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      - name: Run install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files